import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { foxitClient } from "./foxitClient";
import { PDF_TEMPLATES } from "../src/templates";

dotenv.config({ path: "./server/.env" });

const app = express();

app.use(cors());
app.use(express.json({ limit: '50mb' }));

// Logging middleware
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  next();
});

// Router for API routes
const router = express.Router();

// Health check
router.get("/health", (req, res) => {
  res.json({ status: "ok", timestamp: new Date() });
});

// Event Logging Endpoint for Director Mode
router.post("/events", (req, res) => {
  const { eventType, message } = req.body;
  console.log(`[EVENT] ${eventType}: ${message}`);
  res.json({ status: "logged", timestamp: new Date() });
});

// Generate Document Endpoint
router.post("/generate", async (req, res) => {
  try {
    const { templateId, data, services } = req.body;
    console.log("Generating document for:", templateId, "Services:", services);

    // Select the correct template generator or fallback to a simple one
    const templateGen = PDF_TEMPLATES[templateId as keyof typeof PDF_TEMPLATES];
    
    // Inject watermark flag
    const templateData = { 
      ...data, 
      hasWatermark: services?.includes('watermark') 
    };
    
    let htmlContent = '';
    
    if (templateGen) {
      htmlContent = templateGen(templateData);
    } else {
      // Fallback (Simple HTML)
      htmlContent = `
        <html>
          <head>
            <style>
              body { font-family: Helvetica, sans-serif; padding: 40px; }
              h1 { color: #333; border-bottom: 2px solid #fc6408; padding-bottom: 10px; }
              .field { margin-bottom: 15px; }
              .label { font-weight: bold; color: #666; font-size: 12px; text-transform: uppercase; }
              .value { font-size: 16px; color: #000; }
              .footer { margin-top: 50px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
            </style>
          </head>
          <body>
            <h1>${data.name || 'Agreement'}</h1>
            <p><strong>Template ID:</strong> ${templateId} (Fallback Layout)</p>
            
            ${Object.entries(data).map(([key, value]) => `
              <div class="field">
                <div class="label">${key}</div>
                <div class="value">${value}</div>
              </div>
            `).join('')}
  
            <div class="footer">
              Generated by Foxit Sentinel Pro • ${new Date().toLocaleDateString()}
            </div>
          </body>
        </html>
      `;
    }

    // 1. Generate PDF from HTML (DocGen substitute)
    const pdfBuffer = await foxitClient.generatePdfFromHtml(htmlContent);

    // 2. Return the PDF as binary or verify success
    // For the UI, we might want to return a base64 string or just serve the file
    // Let's return base64
    const base64Pdf = pdfBuffer.toString('base64');

    res.json({
      status: "success",
      message: "Document generated successfully",
      pdfBase64: base64Pdf
    });
  } catch (error: any) {
    console.error("Error generating document:", error);
    res.status(500).json({ 
      error: "Failed to generate document", 
      details: error.message,
      stack: error.stack,
      axiosError: error.response?.data
    });
  }
});

// Process Document Endpoint (Watermark/Linearize)
router.post("/process", async (req, res) => {
  try {
    const { pdfBase64, services } = req.body;
    let processedBuffer: any = Buffer.from(pdfBase64, 'base64');

    // Apply services sequentially
    if (services.includes('watermark')) {
      console.log("Applying Foxit Watermark Service...");
      processedBuffer = await foxitClient.applyWatermark(processedBuffer, "CONFIDENTIAL");
    }

    if (services.includes('linearize')) {
      console.log("Linearizing...");
      processedBuffer = await foxitClient.linearizePdf(processedBuffer);
    }

    res.json({
      status: "success",
      message: "Processing complete",
      pdfBase64: processedBuffer.toString('base64')
    });
  } catch (error) {
    console.error("Error processing document:", error);
    res.status(500).json({ error: "Failed to process document" });
  }
});

// Mount Router
// This ensures /api/generate works, AND /generate works (if Vercel strips prefix)
app.use("/api", router);
app.use("/", router);

export default app;
